services:
  - type: web
    name: veterinary-assistant
    env: python
    buildCommand: |
      pip install -r requirements.txt
      mkdir -p uploads
      mkdir -p static/uploads/animals
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: GOOGLE_API_KEY
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: SECRET_KEY
        generateValue: true
    autoDeploy: true
    disk:
      name: uploads
      mountPath: /uploads
      sizeGB: 1
